
=== Chinese

family name + given name(s)

Chinese personal names are names used by those from mainland China, Hong Kong,
Macau, Taiwan, and the Chinese diaspora overseas.

Chinese names consist of a
family name (姓, xìng), followed by
a given name (名, míng).

Some people also utilize a "courtesy name" or "style name" (字, zì),
by which they were known among those outside their
family and closest friends.

[example]
"`孫文`" (Sun Man), the birth name of the founding father
of the Republic of China "`Sun Yat-sen`", where "`孫`" is the family name, "`文`" the given name.

[example]
"`孫德明`" (Sun De Ming), the genealogical name (譜名) of "`Sun Yat-sen`", where "`孫`" is the family name, "`德明`" the given name.

[example]
"`孫帝象`" (Sun Tai Tseung), the pet-name (乳名) of "`Sun Yat-sen`", where "`孫`" is the family name, "`帝象`" the given name.

[example]
"`孫載之`" (Sun Jai Ji), the courtesy name ("`字`") of "`Sun Yat-sen`", where "`孫`" is the family name, "`載之`" the given name.

[example]
"`孫日新`" (Sun Yat Sun), the baptised name of "`Sun Yat-sen`", where "`孫`" is the family name, "`日新`" the given name.

[example]
"`孫逸仙`" (Sun Yat Sen), the art-name ("`號`") of "`Sun Man`", where "`孫`" is the family name, "`逸仙`" the given name.

[example]
"`孫中山`" (Sun Zhongshan), a popular name of "`Sun Yat-sen`", where "`孫`" is the family name, "`中山`" the given name.


[example]
"`宋文初`" is a Chinese pseudonym of "`Hồ Chí Minh`" he used in Hong Kong, where "`宋`" is the family name, "`文初`" the given name.

////
[example]
"`Chen Vang`" is an adopted Chinese pseudonym of "`Hồ Chí Minh`", where "`Chen`" is the family name, "`Vang`" the given name.
////

////
In the first half of the 1st millennium BC, during the Zhou dynasty, members of
the Chinese nobility could possess up to four different names—personal names
(míng 名), clan names (xìng 姓), lineage names (shì 氏), and "style" or
"courtesy" names (zì 字).
////

////
Titles:

* standard title (jué 爵)
* posthumous title (shì 諡 or shìhào 諡號).
////
