
=== English

name components:

- given name
- family name

English names are names used in, or originating in, England. In England as
elsewhere in the English-speaking world, a complete name usually consists of a
given name, commonly referred to as a first name or Christian name, and a (most
commonly patrilineal) family name or surname, also referred to as a last name.

There can be several given names, some of these being often referred to as a
second name, or middle name(s).

Double-barrelled names, compound surnames in English feature two words,
are often joined by a hyphen or hyphens.

==== Typical name patterns

|===
|given name|family name
|===

==== Examples

[example]
Henry Hepburne-Scott

Some families having as many as
three or four words making up their surname.

[example]
====
Charles Hepburn-Stuart-Forbes-Trefusis, 21st Baron Clinton.
====

It is not unusual for compound surnames to be composed of separate words
not linked by a hyphen.

[example]
====
|===
|Iain|Duncan Smith
|given name|family name
|===
====
