
=== Indonesian

given name(s)

Indonesians generally use given names without a family name.
The majority of Indonesians do not have family names. Rather,
their given names are geographically and culturally specific.

[example]
Mulyono, the original name of Joko Widodo.

[example]
Kusno Sosrodihardjo.

[example]
Fransiskus Xaverius Hadi Rudyatmo

[example]
Sudono Salim


////
Names beginning
with "Su" in Indonesian spelling ("Soe" in Dutch orthography), or ending with
an "o" are usually Javanese people. For example, people called "Suprapto" or
"Soeprapto, Joko" are likely to be of Javanese descent. Suharto is another
example.
////

Some given names include a family name or a patronymic.

////
Balinese names are quite distinct, as they have a naming system which denotes
birth order.
////

////
Wayan means first born. Made means second born. A Balinese name
may also indicate caste. For instance, a Kshatriya person may be named "I
Gusti".

"Sitompul" and "Rajagukguk" are clan names usually found in people with Batak
or North Sumatran heritage.
////

Indonesian names usually fall into one of the following categories:

* Mononymic names
* Polynymic names without a family name
* Polynymic names with a family name
* Polynymic names with patronymic


An Indonesian name is often mis-represented in other cultures, such as:

* Netherlands: the word "Onbekend" ("unknown") is assigned as a last name
* Germany: the one-word name is used as both given name and surname
* US: "Fnu" (family name unknown) is assigned as the first or given name, "Lnu" (last name unknown) is assigned as the family, surname or last name,
or the name is duplicated as the surname.

////
Until recently, most Indonesians did not have family names. Both men and women
usually have a given name and then take the name of their father as a last
name. Some, but not all, married Indonesian women take the last name of their
husband. This name is usually added after their own "last" name. Therefore, it
is not rare for married couples to have different last or family names.

Naming also differs regionally. Some Javanese, especially those of the old
generation have only one name. Bataks have clan names which are used as their
surnames. Some Chinese Indonesians have Chinese-style names. In Indonesian
telephone directories, names are listed under the first or given name and not
under the last or family name.
////


