
=== Japanese

family name + given name(s)

Japanese names usually consist of a family name (surname),
followed by a given name.

Japanese names are usually written in kanji,
where characters are logographic, but each with a variety of
possible Japanese pronunciations. Therefore
often names cannot in general be spelled or
pronounced unless both the spelling and pronunciation are given.

TODO: transliteration differences: belongs in here?

[example]
大翔 is traditionally pronounced "Hiroto", but can also be pronounced as
"Haruto", "Yamato", "Taiga", "Sora", "Taito", "Daito", and
"Masato".

[example]
大和 can be read as Daiwa or Yamato.

//(example from W3C)
[example]
東海林 can be read as Tōkairin or Shōji

[example]
"`中山樵`" (Nakayama Sho), the Japanese pseudonym of
"`Sun Yat-sen`":

|===
|中山|樵
|family name |given name
|===

==== Japanese immigrants in Brazil

[example]

|===
|Akemi |Denise |Sameshima
|given name |given name |family name
|===

[example]

|===
|Yuri |Vanessa |Ohara
|given name |given name |family name
|===
