
=== Vietnamese

name components:

- given name
- additional name
- family name


Vietnamese personal names are names used by those from Vietnam and the
Vietnamese diaspora overseas.

Vietnamese names consist of a family name (Tên, 𠸛),
followed by a given name (Họ, /𢩜).
Between the family name and given name,
one or more additional names may be present.

Vietnamese additional names can be a
middle name (tên đệm),
generational name,
or clan distinguisher name. The middle name, for identification purposes, can be omitted.

Courtesy names are also allowed, separate from the given name.

==== Typical name patterns

|===
|given name
|===

|===
|family name|given name
|===

|===
|family name|additonal name|given name
|===


==== Examples

[example]
====
Birth name of "`Hồ Chí Minh`":

|===
|Nguyễn|Sinh Cung
|family name|given name
|===
====


[example]
====
|===
|Hồ|Chí Minh
|family name|given name
|===
====

[example]
====
Another name of "`Hồ Chí Minh`":

|===
|Nguyễn|Tất Thành
|family name|given name
|===
====

[example]
====
A pseudonym of "`Hồ Chí Minh`" ("`Nguyễn the Patriot`"):

|===
|Nguyễn|Ái Quốc
|family name|given name
|===
====

[example]
====
Another name of "`Hồ Chí Minh`" ("`Nguyễn the Patriot`"):

|===
|Nguyễn|Văn|Huệ
|family name|middle name|given name
|===

|===
|Nguyễn|Huệ
|family name|given name
|===
====

[example]
====
|===
|Lê|Tư Thành
|family name|given name
|===
====

[example]
====
|===
|Lê|Hạo
|family name|courtesy name
|===
====
