= CalConnect Standard: Computer applications in terminology -- Naming -- Structure of personal names

This work item belongs to TC VCARD.

ifdef::env-github[]
image:https://img.shields.io/travis/com/CalConnect/csd-name-models/master.svg[
	Build Status, link="https://travis-ci.com/CalConnect/csd-name-models/branches"]
endif::[]

ifdef::env-gitlab[]
image:https://img.shields.io/gitlab/pipeline/ribose/csd-name-models.svg[
  GitLab pipeline, link="https://gitlab.com/ribose/csd-name-models/pipelines"]
endif::[]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-name-models/[CC/ISO: Computer applications in terminology -- Naming -- Structure of personal names (HTML)]

== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/csd-name-models/
----

== Installing Build Tools

=== Metanorma

See https://www.metanorma.com/author/topics/install/

=== Other dependencies

yq::
  https://github.com/mikefarah/yq

NOTE: This can be confused with https://github.com/kislyuk/yq.


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

=== Manual approach

[source,sh]
----
# ... edit source files...
make
----

=== Automatically watch file (experimental)

Spawn a file-watching HTTP server at port 8123:

[source,sh]
----
make watch-serve
----

Spawn a file-watching HTTP server at a specific port:

[source,sh]
----
make watch-serve PORT=8080
----

== Getting help

[source,sh]
----
make help
----
