@startuml

!include style.uml.inc

!definelong primitiveType(x)
rectangle x <<primitiveType>> {
}
!enddefinelong

!definelong dataType(x)
rectangle x <<dataType>> {
}
!enddefinelong

primitiveType(NaturalNumber)
primitiveType(String)
dataType(Iso639Code)
dataType(Iso15924Code)
dataType(Iso24229Code)
dataType(Uri)

class NameString {
  +text: String
}

NaturalNumber -[hidden]- String
Iso639Code    -[hidden]- String
Iso639Code    -[hidden]- Iso15924Code

Iso24229Code  -[hidden]- Uri
NameString    -[hidden]- Uri

@enduml
