@startuml

!include style.uml.inc

interface TemplateFragment {
  +toString(): String
  +component: NameComponent[1..*]
}
note left of TemplateFragment: name components

TemplateFragment -- NameTemplate

class NameTemplate {
  +fragments: TemplateFragment[1..*]
}

class DisplayCriterion {
  ' +predicate: Predicate
}

'note left of DisplayCriterion
'  predicate - needs more thoughts
'  E.g., screen estate, formality
'end note

class NameDisplayProfile {
  +displayTemplate: NameTemplate
  +displayCriteria: DisplayCriterion[1..*]
}
'note bottom: displayCriteria - conjunction or dysjunction?

DisplayCriterion -- NameDisplayProfile
NameTemplate -- NameDisplayProfile

class DisplayProfilePreference {
  +culturalProfiles: Uri[0..*]
}

class CulturalProfile {
  +profileId: Uri
  +displayProfiles: NameDisplayProfile[1..*]
}

DisplayProfilePreference -- PersonalName
DisplayProfilePreference -- CulturalProfile
NameDisplayProfile -- CulturalProfile

@enduml
