@startuml

!include style.uml.inc

class NameComponent {
  +componentId: Uri
  +body: NameString
  +examples: NameString[0..*]
  +abbreviation: NameString[0..*]
  +initials: NameString[0..*]
  +script: Iso15924Code
  +transcription: Iso24229Code
  +language: Iso639Code
}

class FamilyName {
  +type: FamilyNameType[0..*]
}
class GivenName {
  +type: GivenNameType[0..*]
}
class Honorific {
  +type: HonorificType[0..*]
}
class RoleName {
  +type: RoleType[0..*]
}
class AdditionalName {
  +type: AdditionalNameType[0..*]
}
class GenerationalName {
  +type: GenerationalNameType[0..*]
}
class ReligiousName {
  +type: ReligiousNameType[0..*]
}
class Pseudonym {
  +type: PseudonymType[0..*]
}

NameComponent <|-- FamilyName
NameComponent <|-- GivenName
NameComponent <|-- Honorific
NameComponent <|-- RoleName
NameComponent <|-- AdditionalName
NameComponent <|-- GenerationalName
NameComponent <|-- ReligiousName
NameComponent <|-- Pseudonym

FamilyName       -- FamilyNameType
GivenName        -- GivenNameType
Honorific        -- HonorificType
RoleName         -- RoleNameType
AdditionalName   -- AdditionalNameType
GenerationalName -- GenerationalNameType
Pseudonym  -- PseudonymType

enum RoleNameType <<enumeration>> {
  office
  stage
}

enum HonorificType <<enumeration>> {
  academic
}

enum FamilyNameType <<enumeration>> {
  patronymic
  matronymic
}

enum GivenNameType <<enumeration>> {
}

enum AdditionalNameType <<enumeration>> {
}

enum GenerationalNameType <<enumeration>> {
  NaturalNumber
  String
}

enum PseudonymType <<enumeration>> {
  assumed
  stage
  art
  pen
  nickname
  username
  alias
  codename
  regnal
}

@enduml
