@startuml

!include style.uml.inc

class Person {
  +name: PersonalName
}

class PersonalName {
  +components: NameComponent[1..*]
  +displayProfilePreference: DisplayProfilePreference
}

class AnonymousName {
}
class UnknownName {
}


Person -- PersonalName
PersonalName -- AnonymousName
PersonalName -- UnknownName

@enduml

