== Name pattern

=== General

Personal name order depends on the cultural profile of the name.

[example]
The name order of "`[given name(s)] [family name]`" is commonly used
throughout most European countries.

[example]
The name order of "`[family name] [given name(s)]`" is commonly used
in East Asia (for example in China, Japan, Korea, Malaysian
Chinese, Singapore, and Vietnam, among others), as well as in Southern and
North-Eastern parts of India, and in Hungary.

////
This order is common also in
Austria and Bavaria, and in France, Belgium, Greece and Italy, possibly because
of the influence of bureaucracy, which commonly puts the family name before the
given name. In China and Korea, part of the given name may be shared among all
members of a given generation within a family and extended family or families,
in order to differentiate those generations from other generations.
////

[example]
The name order of "`[given name(s)] [father's family name] [mother's family name]`"
is commonly used in Spanish-speaking countries such as Spain and Uruguay.


////
=== Name order systems

There is a range of personal naming systems:

Binomial systems: apart for given name, people are described by their surnames,
which they obtain from one of their parents. Most modern European personal
naming systems, such as Russian and Spanish, are of this type.

Patronymic systems: apart for given name, people are described by their
patronymics, that is given names (not surnames) of parents or other ancestors.
Such systems were in wide us throughout Europe in the first millenium C.E., but
were replaced by binomial systems. Icelandic system is still patronymic.

More complex systems like Arabic system, consisting of paedonymic (son's name),
given name, patronymic and one or two bynames.

Different cultures have different conventions for personal names. This is a
list of articles about particular cultures' naming conventions.
////

=== Abbreviation

The abbreviated forms of a personal name has the following two aspects:

. as a way of presentation, as derived from a non-abbreviated form; and
. as a characterization of data representing the name.
.. In other words, the source of the name is already in an abbreviated form.

[example]
"`Pablo Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso`" becomes "`Pablo Ruiz y Picasso`".

[example]
Ll. George" for (British prime minister) David Lloyd George.

[example]
Names ("FW de Klerk", "GB Whiteley", "Park JS"). A notable exception is The Economist which writes "Mr F. W. de Klerk".

[example]
====
"`Adolph Blaine Charles David Earl Frederick Gerald Hubert Irvin John Kenneth
Lloyd Martin Nero Oliver Paul Quincy Randolph Sherman Thomas Uncas Victor
William Xerxes Yancy Zeus
Wolfe­schlegel­stein­hausen­berger­dorff­welche­vor­altern­waren­gewissen­haft­schafers­wessen­schafe­waren­wohl­gepflege­und­sorg­faltig­keit­be­schutzen­vor­an­greifen­durch­ihr­raub­gierig­feinde­welche­vor­altern­zwolf­hundert­tausend­jah­res­voran­die­er­scheinen­von­der­erste­erde­mensch­der­raum­schiff­genacht­mit­tung­stein­und­sieben­iridium­elek­trisch­motors­ge­brauch­licht­als­sein­ur­sprung­von­kraft­ge­start­sein­lange­fahrt­hin­zwischen­stern­artig­raum­auf­der­suchen­nach­bar­schaft­der­stern­welche­ge­habt­be­wohn­bar­planeten­kreise­drehen­sich­und­wo­hin­der­neue­rasse­von­ver­stand­ig­mensch­lich­keit­konnte­fort­pflanzen­und­sicher­freuen­an­lebens­lang­lich­freude­und­ru­he­mit­nicht­ein­furcht­vor­an­greifen­vor­anderer­intelligent­ge­schopfs­von­hin­zwischen­stern­art­ig­raum
Sr.`"
is also known as:

. Hubert Wolfstern
. Hubert B. Wolfe + 988 Sr.
. Hubert Blaine Wolfe+585 Sr.
. Hubert Blaine Wolfe+590 Sr.
====

////
TODO: Addresses to add abbreviations/contractions
////
