
:sectnums:
== Scope

//TODO

This document specifies the "`personal name`" data model,
suitable for the machine encoding of personal names, for
digital storage and transmission of the following data elements:

* personal name components,

* cultural name profiles for personal name patterns,

* template for displaying personal names.


This document does not handle the linkage of a personal name to an identity.

The personal name model is used to encode a person's personal names for:

* as a static data element
* as an interoperable data structure used with databases

The cultural name profile model is used to guide rendering of a name model instance as a string
as appropriate to the applied cultural name profile.

The usage of this personal name model also applies to the following business cases:

* bibliographic management
* business cards (such as vCard)
* personal identification documents
* electronic messaging, e-commerce
* travel industry
* postal

////
TODO:

* Organize survey of existing personal naming patterns
* Building a set of profiles for cultures
* Display preference profiles for your own names
////
